import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";


const inter = Press_Start_2P({ weight:["400"] ,subsets : ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={inter.className + " bg-orange-400 border-8 border-black min-h-screen flex flex-col"}>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
