import "../globals.css";
import { Noto_Sans_JP } from "next/font/google";
import type { Metadata } from "next";


const inter = Noto_Sans_JP({ weight:["400"] ,subsets : ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <main className={inter.className + " items-center justify-center p-4 lg:p-16"}    >
      <div className="z-10 w-full items-center justify-center flex flex-col lg:flex-row">
        <div className="flex-col text-center lg:max-w-5xl lg:mb-0 lg:text-center p-4 lg:p-16">
          <h1 className={`mb-8 lg:mb-12 text-4xl lg:text-6xl font-semibold`}>
            コンテンツガイドライン
          </h1>
          <section className="border-2 p-6 border-black mb-4">
            <h2 className={`mb-2 lg:mb-4 text-2xl lg:text-4xl font-semibold`}>
              はじめに
            </h2>
            <div>
              このガイドラインは、自身のウェブサイトで二次創作などのコンテンツを公開する際に遵守すべき事項をまとめたものです。二次創作は、Vtuberの活動を広め、ファンとの交流を深める重要な役割を果たします。このガイドラインを遵守することで、Vtuber、ファン、クリエイターの三者が安心して二次創作活動を楽しめる環境を整備することを目的としています。
            </div>
          </section>
          <section className="border-2 p-6 border-black mb-4">
            <h2 className={`mb-2 lg:mb-4 text-2xl lg:text-4xl font-semibold`}>
              1. 適用範囲
            </h2>
            <div>
            このガイドラインは、自身のウェブサイトで公開する二次創作コンテンツに適用されます。二次創作コンテンツには、イラスト、小説、動画、音楽、ゲームなど、あらゆる形式が含まれます。
            </div>
          </section>
          <section className="border-2 p-6 border-black mb-4">
            <h2 className={`mb-2 lg:mb-4 text-2xl lg:text-4xl font-semibold`}>
              2. 基本的なルール
            </h2>
            <div>
              <ul>
                <li>
                  Vtuberのキャラクター性や設定を尊重し、イメージを損なうような表現は避けてください。
                </li>
                <li>
                  公序良俗に反する表現や、差別、誹謗中傷を含む表現は禁止です。
                </li>
                <li>
                  著作権や肖像権などの他者の権利を侵害するような行為は禁止です。
                </li>
                <li>
                  Vtuberやファンのプライバシーを侵害するような行為は禁止です。
                </li>
                <li>
                  二次創作作品を公開するためには、あらかじめ本ガイドラインのすべてをお読みいただき、本ガイドラインに同意いただく必要があります。
                </li>
                <li>
                  みなさまが本コンテンツの二次創作作品を公開した時点で、本ガイドラインの内容のすべてに同意をしていただいたものとみなします。
                </li>
                <li>
                  本ガイドラインの内容に沿う形であれば、二次創作作品の公開についての申請や連絡は不要です。二次創作文化における最低限のマナーを守って、ご自由に二次創作活動をお楽しみください。
                </li>
                <li>
                  許諾を得た場合でも、Vtuberは二次創作コンテンツに対して修正や削除を依頼する権利を有します。
                </li>
              </ul>
            </div>
          </section>
          <section className="border-2 p-6 border-black mb-4">
            <h2 className={`mb-2 lg:mb-4 text-2xl lg:text-4xl font-semibold`}>
              3. クレジット表記
            </h2>
            <div>
              <ul>
                <li>
                  二次創作コンテンツには、必ず以下のクレジットを明記してください。
                </li>
                <li>
                  Vtuberの名前                
                </li>
                <li>
                  二次創作コンテンツの作者名
                </li>
                <li>
                  ただし、集合写真のような形での作品の場合は作品内に書く必要はございません。
                </li>
              </ul>
            </div>
          </section>
          <section className="border-2 p-6 border-black mb-4">
            <h2 className={`mb-2 lg:mb-4 text-2xl lg:text-4xl font-semibold`}>
              4. 商用利用について
            </h2>
            <div>
              二次創作コンテンツを商用利用する場合には、事前にVtuberに許諾を得る必要があります。
            </div>
          </section>
          <section className="border-2 p-6 border-black mb-4">
            <h2 className={`mb-2 lg:mb-4 text-2xl lg:text-4xl font-semibold`}>
              5. その他
            </h2>
            <div>
              このガイドラインは予告なく変更される場合があります。
            </div>
          </section>
          <section className="border-2 p-6 border-black mb-4">
            <h3>免責事項</h3>
            <span>このガイドラインは、法的拘束力を持つものではありません。二次創作活動を行う際には、個人の責任において、著作権法やその他の法令を遵守してください。</span>
          </section>
          <section className="border-2 p-6 border-black mb-4">
            <h3>制定日</h3>
            <span>2024年2月13日</span>
          </section>
          <section className="border-2 p-6 border-black mb-4">
            <h3>改定履歴</h3>
            <span>2024年2月13日: 初版公開</span>
          </section>
        </div>
      </div>
    </main>
  );
}
